load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "lib",
    hdrs = [
        "buffered_fd_reader.h",
    ],
    srcs = [
        "buffered_fd_reader.cpp",
    ],
    visibility = ["//visibility:public"],
)